name: Docs

on: 
  - push
  - workflow_dispatch


permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  docs:
    run: Build and deploy docs
    uses: alephdata/astro-theme-docs/.github/workflows/docs.yml@main
    permissions:
      contents: read
      pull-requests: write
    with:
      build-path: ./docs
      deploy: ${{ github.ref == 'refs/heads/main' }}
