name: Docs

on: 
  - push
  - workflow_dispatch

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  docs:
    name: Build and deploy docs
    uses: alephdata/astro-theme-docs/.github/workflows/docs.yml@main
    permissions:
      contents: read
      pages: write
      id-token: write
    with:
      build-path: ./docs
      deploy: ${{ github.ref == 'refs/heads/main' }}
